### ISSUE TITLE
algebra.primitive_root always raise AssertionError

### ISSUE THREAD

**Issue by Terryobeyes** [cheran-senthil/PyRival#28]
Hi, I'm a codeforces pupil from Taiwan
My English isn't very good, please don't mind

This module has taught me a lot
I really hope this module become better
But some of the functions I don’t know how to use
Hope there are some samples to read

Then, I don't know where else to leave a message
Just happened to find a bug
Hope it didn't bother you

**Comment by cheran-senthil** [comment]
Sorry I didn't see this sooner.

Thanks for your interest, we are in the process of adding new tests, and hopefully, documentation will follow soon after.

Thank you very much for pointing out the issue, I did not realize that this code never worked in the first place, I'll see if I can find a fix later this week.

**Comment by cheran-senthil** [comment]
Thanks again, fixed and merged.
