### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by harshraj22** [cheran-senthil/PyRival#34]
<h3> Suggestion </h3>

It would be helpful if [this](https://codeforces.com/blog/entry/74750?#comment-588920) codeforces comment link is added to the [bootstrp.py](https://github.com/cheran-senthil/PyRival/blob/master/pyrival/misc/bootstrap.py) file as a reference as just by looking at the file, it might be hard to understand what it is ment for.

BTW, is it for all (`pypy`, `pypy3`, `python2`, `python3`) ?

**Comment by cheran-senthil** [comment]
Please see, https://pyrival.readthedocs.io/

The main repo is intended to be Python 3.
