### ISSUE TITLE
Please provide getting started instructions

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [cheran-senthil/PyRival#45]
It is difficult to figure out how to use this library.

**Comment by Shaikh-Ubaid** [comment]
I am not getting enough idea how to start using this. The only thing that I can understand is that we can use master template for FASTIO and submit solutions with pypy 2.7 on codeforces. Since, this library is available on pypy docs, can we do something like `import pyrival` on codeforces/codechef/hackerrank.

**Comment by bjorn-martinsson** [comment]
That is not how Python works. You can only import modules that are installed. So locally you can make `import pyrival` work after installing it with `pip install PyRival `. Platforms like codeforces/codechef/hackerrank however will not have it installed. Even relatively standard libraries like numpy is usually missing on online platforms.

For competitive programming, the intended way to use this library is to look up the stuff you need and copy paste it into your code.

**Comment by cheran-senthil** [comment]
We might add more documentation later, but right now, this is not a priority.
