### ISSUE TITLE
Generate snippets/plugins for the main IDEs

### ISSUE THREAD

**Issue by janLuke** [cheran-senthil/PyRival#51]
Instead of manually looking for a function/class and copy-pasting it, it'd be great to have snippets for each of them. It should be easy to generate snippets for the main IDEs using `inspect`.

**Comment by Mukundan314** [comment]
I don't think this should be a part of the PyRival repo; I am open to discussion on this.

However, please feel free to create an extension for this.

**Comment by janLuke** [comment]
Sorry, I forgot to reply. I think pyrival makes sense more as a set of snippets than as package / reusable library. Please, correct me if I'm wrong. So I thought it might be reasonable to have snippets/plugins for all IDEs all in this repo, mainly to facilitate automation of snippet generation when pyrival code is modified. Nonetheless, I'm not really sure if a "monorepo" would be an advantage wrt having "plugin repos" all listening to this "code repo".

**Comment by cheran-senthil** [comment]
I think I would prefer a philosophy of keeping it simple; over making this a general repo that can do a lot of things.

If you decide to make a repo that has plugins for editor support, I would be happy to add a link from PyRival. However, I do not think I would want this within the main repo.

**Comment by janLuke** [comment]
Okay :)
