### ISSUE TITLE
Adding a brief explanation for Algorithms and concepts.

### ISSUE THREAD

**Issue by Dude-901** [cheran-senthil/PyRival#53]
**Is your feature request related to a problem? Please describe.**
A brief explanation for programs using comments or a separate readme file or even reference links would be a great addition to this repo.

**Describe the solution you'd like**
The explanations could be added in any form suitable to the repo managers, like proper commenting, a common readme file for all, directory-wise readme files, or a separate one for each concept.

**Describe alternatives you've considered**

**Additional context**
I would also like to contribute to this repo some time in the near future as I've just begun my competitive programming journey.

**Comment by cheran-senthil** [comment]
Though example usage would be nice to have; I do not have the time to add examples for the scripts available in this repo.

I assume that most people using PyRival have already reached the limits of competitive programming in Python and would be familiar with most of the algorithms provided here.

However, we already have a [docs](https://github.com/cheran-senthil/PyRival/tree/master/docs) section in the repo. Currently, this is quite limited and only documents the bootstrap function which happens to be somewhat nontrivial in its implementation.

Please feel free to open a PR to the repo if you would like to contribute.
