### ISSUE TITLE
Generate snippets for the editors

### ISSUE THREAD

**Issue by fixxtion** [cheran-senthil/PyRival#60]
### So, I am working on plugins for vs code, sublime text and I have idea for creating  a little unique approach to implement extensions for browsers too.

I use VS code most so i made a extension for it to generate snippets. If you would like to check the extension, links for the same are given below.
https://github.com/fixxtion/vscode-pyrival
https://marketplace.visualstudio.com/items?itemName=fixxtion.py-rival

I am new to the game, please guide me and should i proceed further?

**Comment by cheran-senthil** [comment]
This is pretty cool!

This repository is meant to be a source of code, and I would prefer not to include competitive programming-specific tooling into it. However, for your repo, please feel free to continue work as you think suitable

**Comment by cheran-senthil** [comment]
See also: https://github.com/cheran-senthil/PyRival/issues/51
