### ISSUE TITLE
Output Fails to Match even though it's Correct and Accepted when using CPH Judge and Competitive Companion Extension for VS Code

### ISSUE THREAD

**Issue by shardul-rajhans** [cheran-senthil/PyRival#71]
**Python Version:** 3.8.3

**Description**
1. Using the Master Sample Template, the [CPH Judge](https://chrome.google.com/webstore/detail/competitive-companion/cjnmckjndlpiamhfimnnjmnckgghkjbl) extension for VS Code doesn't match the output, even though it's correct and accepted in CodeForces.
2. I am sharing the [Exact Code](https://codeforces.com/contest/1634/submission/145498939) and the [Problem Statement](https://codeforces.com/contest/1634/problem/A).

**Comment by bjorn-martinsson** [comment]
1. What exactly is the difference in output? 
2. If you do not use pyrivals template, do you still get the same problem?

**Comment by shardul-rajhans** [comment]
1. I have checked for trimmed spaces or everything but couldn't find any difference. To confirm this, I have checked the output values in a diff checker, it also matches everything perfectly fine.

2. If I don't use pyrivals template, then the test cases are in Passed State.

Now, as we are modifying the sys.stdout, is the pyrivals template really compatible with the Competitive Companion Extension?
I am adding the snapshots of the observations for better understanding. Even I can submit the code as it is and it gets accepted. But for me, it's bothering that the test cases are not passed with using the above extension. It will be better if you provide any suggestion or quick fix. Even, I will be more obliged if you recommend any other compatible extension with the template.


![WithTemplateOutputDiff](https://user-images.githubusercontent.com/38533821/152776841-410591e2-5083-4f6b-8a2b-3a3e0a7c475a.png)
![WithoutTemplate](https://user-images.githubusercontent.com/38533821/152776843-36419f0d-1893-4c61-bbcf-4fbaf532f28a.png)
![WithTemplate](https://user-images.githubusercontent.com/38533821/152776848-6195f690-3bc7-465a-9327-f8e1b049b6c3.png)

**Comment by bjorn-martinsson** [comment]
> 1. I have checked for trimmed spaces or everything but couldn't find any difference. To confirm this, I have checked the output values in a diff checker, it also matches everything perfectly fine.

This makes me suspect the issue is windows newlines vs linux newlines. Which operating system are you running? And can you check if that is the difference? Here is the Python 3 script that I normally use to detect windows newlines vs linux newlines in a file

```py
import sys
print(sys.stdin.buffer.read())
```

> Now, as we are modifying the sys.stdout, is the pyrivals template really compatible with the Competitive Companion Extension?

The template is just using os.write, which is what sys.stdout is using internally anyways. So that part of the template should not be able to cause any kind of incompabilities. That said, I don't know how the Competitive Companion Extension works. If anything this feels more like a bug on their side than ours.

**Comment by shardul-rajhans** [comment]
However, if you can recommend a tool for Codeforces Contests solutions output matching in any of the editor, it will be helpful for me.
Thanks.

**Comment by cheran-senthil** [comment]
It is not in our best interest to look or support other extensions since a good extension today will not be a good extension tomorrow.

I think the problem is just with Windows carriage line returns, and likely an issue with the extension handling this incorrectly.

**Comment by bjorn-martinsson** [comment]
I just wanted to add two final remarks. 

1. The template you have been using is a template made to run Python 3 code in Python 2. If you just want to code and run Python 3 code you should not use this template.

2. If you still want to use to use this template, then the fix is to change

```py
file.write(kwargs.pop("end", "\n"))
``` 

to 

```py
file.write(kwargs.pop("end", "\r\n"))
```
