### ISSUE TITLE
The new SortedList method naming scheme is not user friendly

### ISSUE THREAD

**Issue by heidenrei** [cheran-senthil/PyRival#75]
The old method names were better as they directly copied sortedcontainers. Using multiset method names is annoying.

**Comment by bjorn-martinsson** [comment]
Can you be more specific?

**Comment by bogoconic1** [comment]
SortedList in python uses bisect_left (not lower_bound) and bisect_right (not upper_bound)
lower_bound and upper_bound is the method names for C++ and many python users arent very good at it, which makes it very confusing

**Comment by Mukundan314** [comment]
A remove method would be good as `s.pop(s.lower_bound(val))` is not so obvious
